# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "test_example.ipynb",
         "say_goodbye": "00_core.ipynb"}

modules = ["core.py",
           "test_example.py"]

doc_url = "https://daviderzmann.github.io/designkit_test/"

git_url = "https://github.com/daviderzmann/designkit_test/tree/master/"

def custom_doc_links(name): return None
